/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.guessgame;

import id.co.indocyber.guessgame.model.WordModel;
import id.co.indocyber.guessgame.model.WordQuestionGenerator;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author user
 */
public class GuessingGame extends javax.swing.JFrame {
WordModel modelWord;
//String [] bankSoal = {"Pondok Indah", "Sudirman","Tugu Tani", "Citos", "Gandaria City"};
//WordModel soal1 = new WordModel ("Pondok Indah","Daerah di Jakarta Selatan");
//WordModel soal2 = new WordModel ("Sudirman","Jalan Utama di Jakarta");
//WordModel soal3 = new WordModel ("Tugu Tani","Patung Dekat Monas");
//WordModel soal4 = new WordModel ("Citos","Mall di Jakarta Selatan");
//WordModel soal5 = new WordModel ("Gandaria City","Mall anak muda");
//WordModel[] bankSoal = {soal1, soal2, soal3, soal4, soal5}; 
   List<WordModel> bankSoal;
/**
     * Creates new form GuessingGame
     */
    public GuessingGame() {
        bankSoal = WordQuestionGenerator.createQuestionInCollection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soalTextField = new javax.swing.JTextField();
        jawabanTextField = new javax.swing.JTextField();
        checkAnswerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comentLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        hintButton = new javax.swing.JButton();
        hintLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        soalTextField.setEditable(false);

        checkAnswerButton.setText("Periksa");
        checkAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnswerButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Jawaban :");

        comentLabel.setText("Belum ada jawaban");

        startButton.setText("MULAI");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        hintButton.setText("Bantuan");
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });

        hintLabel.setText("Hint");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(soalTextField)
                    .addComponent(jawabanTextField)
                    .addComponent(checkAnswerButton)
                    .addComponent(jLabel1))
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hintButton)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(comentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(hintLabel)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(hintButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(hintLabel)
                .addGap(18, 18, 18)
                .addComponent(soalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkAnswerButton)
                .addGap(18, 18, 18)
                .addComponent(comentLabel)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        int soalIndex = (int) Math.floor(Math.random() * bankSoal.size());
        modelWord = bankSoal.get(soalIndex);
        soalTextField.setText(modelWord.acakHuruf());
        
//        basicWord = basicWord.toUpperCase();
//        String[] arrayOfWord = basicWord.split("");
//        
//        for (int i =0; i < arrayOfWord.length; i++){
//            System.out.println(arrayOfWord[i]);
//        }
//        // string mempunyai lenght, split gunanya untuk memisahkan string
//        Arrays.sort(arrayOfWord);
//        StringBuilder sb = new StringBuilder(); // mengubah array menjadi string
//        System.out.println("\n setelah disort");
//        for (int i =0; i < arrayOfWord.length; i++){
//        //    System.out.println(arrayOfWord[i]);
//        // sort gunanya untuk mengurutkan array mulai huruf besar ke kecil A-Z
//        sb.append(arrayOfWord[i]); // append gunanya untuk mengubah array menjadi string
//        }
//        String soal = sb.toString();
//            System.out.println("Soal yang harus di jawab : " + soal.trim());
            
    }//GEN-LAST:event_startButtonActionPerformed

    private void checkAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnswerButtonActionPerformed
        // TODO add your handling code here:
        String jawaban = jawabanTextField.getText().trim();
        modelWord.setJawaban(jawaban);
                if (modelWord.cekJawaban()){
            comentLabel.setText("Jenius!");
        } else {
            comentLabel.setText("Coba Lagi");
        }
    }//GEN-LAST:event_checkAnswerButtonActionPerformed

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
        // TODO add your handling code here:
        hintLabel.setText(modelWord.getHint());
    }//GEN-LAST:event_hintButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkAnswerButton;
    private javax.swing.JLabel comentLabel;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jawabanTextField;
    private javax.swing.JTextField soalTextField;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
